### ISSUE TITLE
iTunes Banner Notifications not showing after patch

### ISSUE THREAD

**Issue by CFarzaneh** [thebitguru/play-button-itunes-patch#25]
After patching rcd with the Play Button iTunes Patch GUI, iTunes no longer displays a banner notification when the song changes but the notification still pins in Notification Center. 

Unpatching it fixes this

**Comment by thebitguru** [comment]
That's quite surprising because the patch is relatively simple and shouldn't impact the notifications in any way.  I just tried it on my local machine (OS X 10.10.5, Build 14F27) and I still see the banner even with `rcd` patched.  Are you sure there isn't anything else on your system that could be preventing it?
